server:
  port: 8081

spring:
  datasource:
    url: ${ORACLE_URI:jdbc:mysql:thin:@localhost:1521/XE}
    username: ${ORACLE_USER:doubledi_iam}
    password: ${ORACLE_PASSWORD:Doubledi}
    hikari:
      maximum-pool-size: ${CONNECTION_POOL_SIZE:10}