server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: iam
  datasource:
    driver-pass-name: org.postgresql.Driver
#    url: ${POSTGRES_URI:jdbc:postgresql://localhost:5432/DOUBLEDI_IAM?currentSchema=DOUBLEDI_IAM&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true}
    url: jdbc:postgresql://localhost:5432/XE
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
